"""Guest Email and Display_name

Revision ID: 5476d407fb28
Revises: d00801e71c80
Create Date: 2026-02-16 10:56:34.464932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5476d407fb28'
down_revision: Union[str, Sequence[str], None] = 'd00801e71c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_conversations', 'label',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('chat_messages', sa.Column('guest_display_name', sa.String(length=120), nullable=True))
    op.add_column('chat_messages', sa.Column('guest_contact_email', sa.String(length=255), nullable=True))
    op.alter_column('chat_participants', 'display_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('chat_participants', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_participants', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('chat_participants', 'display_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('chat_messages', 'guest_contact_email')
    op.drop_column('chat_messages', 'guest_display_name')
    op.alter_column('chat_conversations', 'label',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
