"""Rating And Timing

Revision ID: 723074c592c1
Revises: bec7ffc4749a
Create Date: 2026-02-22 12:16:03.398333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723074c592c1'
down_revision: Union[str, Sequence[str], None] = 'bec7ffc4749a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('first_response_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_conversations', 'first_response_seconds')
    # ### end Alembic commands ###
