"""Add File

Revision ID: bec7ffc4749a
Revises: 025662afb96b
Create Date: 2026-02-22 11:10:27.280103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec7ffc4749a'
down_revision: Union[str, Sequence[str], None] = '025662afb96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.alter_column('chat_messages', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('chat_messages', 'file_url')
    # ### end Alembic commands ###
