"""remove Role

Revision ID: bed9ae616c9f
Revises: 9217c91ec799
Create Date: 2026-02-08 10:43:37.019062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bed9ae616c9f'
down_revision: Union[str, Sequence[str], None] = '9217c91ec799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_codes_otp_session_id'), table_name='otp_codes')
    op.create_index(op.f('ix_otp_codes_otp_session_id'), 'otp_codes', ['otp_session_id'], unique=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('SUPERADMIN', 'ADMIN', name='userrole'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_otp_codes_otp_session_id'), table_name='otp_codes')
    op.create_index(op.f('ix_otp_codes_otp_session_id'), 'otp_codes', ['otp_session_id'], unique=True)
    # ### end Alembic commands ###
