"""Add Tables

Revision ID: d00801e71c80
Revises: a7f19c840dc3
Create Date: 2026-02-13 16:31:22.498674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00801e71c80'
down_revision: Union[str, Sequence[str], None] = 'a7f19c840dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='conversation_status'), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('assigned_agent_user_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_assigned_agent_user_id'), 'chat_conversations', ['assigned_agent_user_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_label'), 'chat_conversations', ['label'], unique=False)
    op.create_index(op.f('ix_chat_conversations_status'), 'chat_conversations', ['status'], unique=False)
    op.create_table('chat_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'agent', name='participant_role'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(user_id IS NOT NULL AND guest_id IS NULL) OR (user_id IS NULL AND guest_id IS NOT NULL)', name='ck_chat_participants_exactly_one_identity'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'role', name='uq_chat_participants_conversation_role')
    )
    op.create_index(op.f('ix_chat_participants_conversation_id'), 'chat_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_participants_guest_id'), 'chat_participants', ['guest_id'], unique=False)
    op.create_index(op.f('ix_chat_participants_role'), 'chat_participants', ['role'], unique=False)
    op.create_index(op.f('ix_chat_participants_user_id'), 'chat_participants', ['user_id'], unique=False)
    op.create_table('chat_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('agent_user_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_ratings_agent_user_id'), 'chat_ratings', ['agent_user_id'], unique=False)
    op.create_index(op.f('ix_chat_ratings_conversation_id'), 'chat_ratings', ['conversation_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_participant_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_participant_id'], ['chat_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_conversation_created_at', 'chat_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_participant_id'), 'chat_messages', ['sender_participant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_sender_participant_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_conversation_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_ratings_conversation_id'), table_name='chat_ratings')
    op.drop_index(op.f('ix_chat_ratings_agent_user_id'), table_name='chat_ratings')
    op.drop_table('chat_ratings')
    op.drop_index(op.f('ix_chat_participants_user_id'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_role'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_guest_id'), table_name='chat_participants')
    op.drop_index(op.f('ix_chat_participants_conversation_id'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('ix_chat_conversations_status'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_label'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_assigned_agent_user_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
